export const IMAGE_SEARCH_DUCKDUCKGO = 'IMAGE_SEARCH_DUCKDUCKGO'
export const IMAGE_SEARCH_DUCKDUCKGO_SUCCESS = 'IMAGE_SEARCH_DUCKDUCKGO_SUCCESS'
export const IMAGE_SEARCH_DUCKDUCKGO_ERROR = 'IMAGE_SEARCH_DUCKDUCKGO_ERROR'
export const RESET_IMAGE_RESULT_DUCKDUCKGO = 'RESET_IMAGE_RESULT_DUCKDUCKGO'

export const IMAGE_SEARCH_GOOGLE = 'IMAGE_SEARCH_GOOGLE'
export const IMAGE_SEARCH_GOOGLE_SUCCESS = 'IMAGE_SEARCH_GOOGLE_SUCCESS'
export const IMAGE_SEARCH_GOOGLE_ERROR = 'IMAGE_SEARCH_GOOGLE_ERROR'
export const RESET_IMAGE_RESULT_GOOGLE = 'RESET_IMAGE_RESULT_GOOGLE'

export const IMAGE_UPLOAD = 'IMAGE_UPLOAD'
export const IMAGE_UPLOAD_SUCCESS = 'IMAGE_UPLOAD_SUCCESS'
export const IMAGE_UPLOAD_ERROR = 'IMAGE_UPLOAD_ERROR'
