export const IMAGE_SEARCH_DUCKDUCKGO = 'IMAGE_SEARCH_DUCKDUCKGO'
export const IMAGE_SEARCH_DUCKDUCKGO_SUCCESS = 'IMAGE_SEARCH_DUCKDUCKGO_SUCCESS'
export const IMAGE_SEARCH_DUCKDUCKGO_ERROR = 'IMAGE_SEARCH_DUCKDUCKGO_ERROR'
export const RESET_IMAGE_RESULT_DUCKDUCKGO = 'RESET_IMAGE_RESULT_DUCKDUCKGO'
