export const TMDB_SEARCH_MOVIE = 'TMDB_SEARCH_MOVIE'
export const TMDB_SEARCH_MOVIE_SUCCESS = 'TMDB_SEARCH_MOVIE_SUCCESS'
export const TMDB_SEARCH_MOVIE_ERROR = 'TMDB_SEARCH_MOVIE_ERROR'

export const TMDB_MOVIE_DETAIL = 'TMDB_MOVIE_DETAIL'
export const TMDB_MOVIE_DETAIL_SUCCESS = 'TMDB_MOVIE_DETAIL_SUCCESS'
export const TMDB_MOVIE_DETAIL_ERROR = 'TMDB_MOVIE_DETAIL_ERROR'

export const TMDB_MOVIE_IMAGE = 'TMDB_MOVIE_IMAGE'
export const TMDB_MOVIE_IMAGE_SUCCESS = 'TMDB_MOVIE_IMAGE_SUCCESS'
export const TMDB_MOVIE_IMAGE_ERROR = 'TMDB_MOVIE_IMAGE_ERROR'
