export const FETCH_SHOWS = 'FETCH_SHOWS'
export const FETCH_SHOWS_SUCCESS = 'FETCH_SHOWS_SUCCESS'
export const FETCH_SHOWS_ERROR = 'FETCH_SHOWS_ERROR'

export const FETCH_SHOW = 'FETCH_SHOW'
export const FETCH_SHOW_SUCCESS = 'FETCH_SHOW_SUCCESS'
export const FETCH_SHOW_ERROR = 'FETCH_SHOW_ERROR'
